language: php

php:
  - 7.2
  - 7.4

before_script:
  - composer require --dev cakephp/cakephp-codesniffer:dev-master
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=config/Migrations/* ./src ./config

notifications:
  email: false
